### ISSUE TITLE
Add pull requests template

### ISSUE THREAD

**Issue by Tractorou24** [Tractorou24/spark#5]
As a **developer**, I want to be able to make, review and merge pull requests without forgetting steps.

### **Acceptance Criteria:**
- Scenario:
    - When creating a pull request on the SPARK repository
    - Then it should automatically write it to the description field

**Comment by okaydivyansh** [comment]
#17 I have tried to solve the issues by adding the pull request template.

**Comment by Tractorou24** [comment]
Closes #5
